### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by merks**
Use Mylyn's badge and link to the configuration.

### CODE REVIEW

**Comment by merks** [comment]
@BeckerFrank I tested that this actually works. 😄

**Comment by BeckerFrank** [comment]
> @BeckerFrank I tested that this actually works. 😄

So I close this Pull Request!

**Comment by merks** [comment]
But you closed it without committing the change!  😱 

It seems I can't reopen it...  😭

**Comment by merks** [comment]
Better. 😀

**Comment by merks** [comment]
No need to be sorry!  I spent 20 minutes trying to figure out how to commit to a submodule just now, which turned out to be kind of trivial and even semi-obvious...

**Pull request merged**
